static_users:
  - first_name: Olli
    last_name: Owner
    email: olli.owner@metal-stack.io
    password: Olli.Owner123!
  - first_name: Gerrit
    last_name: Guest
    email: gerrit.guest@metal-stack.io
    password: Gerrit.Guest123!
project:
  id: metal-stack
  name: metal-stack
application:
  # later id will be added but currently not possible with zitadel
  id: metal-stack
  name: metal-stack
  redirect_uri: http://v2.api.172.17.0.1.nip.io:8080/auth/openid-connect/callback
generic_oidc_providers:
  - name: keycloak
    issuer: issuer
    client_id: client-id
    client_secret: client-secret
    is_auto_create: true
    is_auto_update: true
